### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by hahahahahahahahahahahahahahahah** [alpha1e0/kiwi#9]
```
$ python2 kiwi.py -o sch.html -t "/storage/emulated/0/hahaha/sch-backup/" -f "/storage/emulated/0/hahaha/kiwi/kiwi_data/features/php.feature"
+------------------------------------------------------------------------------+
|                 Kiwi. Security tool for auditing source code                 |
|                       https://github.com/alpha1e0/kiwi                       |
+------------------------------------------------------------------------------+

[Kiwi 代码安全扫描]
--------------------------------------------------------------------------------
[i]: kiwi 扫描 /storage/emulated/0/for-termux/sch-backup ...
Traceback (most recent call last):
  File "kiwi.py", line 16, in <module>
    main()
  File "/data/data/com.termux/files/home/kiwi/kiwi/kiwi/ui/cli/main.py", line 92, in main
    Analyzer().analyze()
  File "/data/data/com.termux/files/home/kiwi/kiwi/kiwi/core/analyzer.py", line 26, in analyze
    filemgr.init()                                                      File "/data/data/com.termux/files/home/kiwi/kiwi/kiwi/core/filemgr.py", line 157, in init
    self._load_map_conf()
  File "/data/data/com.termux/files/home/kiwi/kiwi/kiwi/core/filemgr.py", line 170, in _load_map_conf
    config = YamlConf(conf.mapfile)
  File "/data/data/com.termux/files/home/kiwi/kiwi/kiwi/core/common.py", line 40, in __new__
    "Loading yaml file '{0}' failed, read file failed".format(path))
kiwi.core.exception.FileError: FileError: 0
$
```
```
$ uname -a
Linux localhost 4.9.112-perf-g495fd4d #1 SMP PREEMPT Sat Jan 11 23:56:03 CST 2020 aarch64 Android
```
android 9
miui 11
```
$ pwd
/data/data/com.termux/files/home/kiwi/kiwi
$ ls
MANIFEST.in  dist  kiwi-report.py  kiwi.py           setup.py
build        kiwi  kiwi.egg-info   requirements.txt
$
```

**Comment by hahahahahahahahahahahahahahahah** [comment]
我在用这个app 不知道是不是因為这个app的环境所致 你先载来试试看吧~
https://play.google.com/store/apps/details?id=com.termux
https://play.google.com/store/apps/details?id=com.termux.api

**Comment by hahahahahahahahahahahahahahahah** [comment]
https://wiki.termux.com
https://termux.com
https://github.com/termux

**Comment by alpha1e0** [comment]
试试：
python2 kiwi.py -o sch.html -t "/storage/emulated/0/for-termux/sch-backup/" -f "/storage/emulated/0/for-termux/kiwi/kiwi_data/"
